services:
  - type: web
    name: pixeltalk-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_DISPLAY_NAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: EMAIL_FROM
        value: PixelTalk <skgamerpro123@gmail.com>
      - key: BREVO_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MAX_FILE_SIZE_MB
        value: 25
